### PR TITLE
throw an error when polling if notion returns one

### PR DESCRIPTION
**Pull request by mattcasey**
I was testing out this code, and noticed it was never returning due to an error.

### CODE REVIEW

**Comment by Devorein** [comment]
@mattcasey Thank you for the PR. That honestly skipped my mind while I was writing it, the fact that a task might also respond with a failed state. I think I'll have to add type defs in types/tasks.ts file to consider the fail state of each task response. Right now it's only been added for a few task responses thus the tests fail and ultimately the build fails.

**Comment by Devorein** [comment]
@mattcasey If you can integrate failure state typedefs for all tasks that'd be wonderful. If not, I'll just merge this PR and add the typedefs by myself.

**Comment by mattcasey** [comment]
@Devorein i will. I'm sorry I just did a text search for that line, it looks like no one's actually using `TaskState`!

**Comment by Devorein** [comment]
@mattcasey No problem. I've added the necessary types defs in tasks and it has been merged in the repo.

**Pull request merged**
